const DELETE_DATA_MESSAGE = "DATA DELETED SUCCESSFULLY";
const UPDATE_DATA_MESSAGE = "DATA UPDATED SUCCESSFULLY";
const INTERNAL_SERVER_ERROR_MESSAGE = "INTERNAL SERVER ERROR";
const POST_DATA_MESSAGE = "DATA ADDED SUCCESSFULLY";

export {
    DELETE_DATA_MESSAGE,
    UPDATE_DATA_MESSAGE,
    INTERNAL_SERVER_ERROR_MESSAGE,
    POST_DATA_MESSAGE
};

